CREATE TABLE dictionary
    (
        WORD VARCHAR(50) NOT NULL,
        TRANSLATION VARCHAR(20000) NOT NULL,
        CONSTRAINT DICTIONARY_PK PRIMARY KEY (WORD)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8